AMNYTAS = 1517
ARBORSTONE = 1428
AURIC_BASIN = 1043
BITTERFROST_FRONTIER = 1178
BJORA_MARCHES = 1343
BLACK_CITADEL = 218
BLAZERIDGE_STEPPES = 20
BLOODSTONE_FEN = 1165
BLOODTIDE_COAST = 73
BRISBAN_WILDLANDS = 54
CALEDON_FOREST = 34
CELESTIAL_CHALLENGE = 1353
CLAW_ISLAND = 335
CRYSTAL_OASIS = 1210
CURSED_SHORE = 62
DESERT_HIGHLANDS = 1211
DIESSA_PLATEAU = 32
DIVINITYS_REACH = 18
DOMAIN_OF_ISTAN = 1263
DOMAIN_OF_KOURNA = 1288
DOMAIN_OF_VABBI = 1248
DRACONIS_MONS = 1195
DRAGON_BASH_ARENA = 1326
DRAGONFALL = 1317
DRAGONS_END = 1422
DRAGONS_STAND = 1041
DREDGEHAUNT_CLIFFS = 26
DRIZZLEWOOD_COAST = 1371
DRY_TOP = 988
ELON_RIVERLANDS = 1228
EMBER_BAY = 1175
EYE_OF_THE_NORTH = 1370
FIELDS_OF_RUIN = 21
FIREHEART_RISE = 22
FROSTGORGE_SOUND = 30
GENDARRAN_FIELDS = 24
GROTHMAR_VALLEY = 1330
GYALA_DELVE = 1490
HARATHI_HINTERLANDS = 17
HEART_OF_THE_MISTS = 350
HOELBRAK = 326
IRON_MARCHES = 25
JAHAI_BLUFFS = 1301
KESSEX_HILLS = 23
LABYRINTHINE_CLIFFS = 922
LAKE_DORIC = 1185
LIONS_ARCH = 50
LIONS_ARCH_AERODROME = 1155
LORNARS_PASS = 27
MAD_KINGS_LABYRINTH = 866
MAD_KINGS_RACEWAY = 1304
MALCHORS_LEAP = 65
MEMORY_OF_OLD_LIONS_ARCH = 1483
METRICA_PROVINCE = 35
MISTLOCK_SANCTUARY = 1206
MISTS_RIFT = 1316
MOUNT_MAELSTROM = 39
NEW_KAINENG_CITY = 1438
NOBLES_FOLLY = 1158
PLAINS_OF_ASHFORD = 19
QUEENSDALE = 15
RATA_SUM = 139
SANDSWEPT_ISLES = 1271
SEITUNG_PROVINCE = 1442
SIRENS_LANDING = 1203
SKYWATCH_ARCHIPELAGO = 1510
SNOWDEN_DRIFTS = 31
SOUTHSUN_COVE = 873
SPARKFLY_FEN = 53
SPIRIT_VALE = 1147
STRAITS_OF_DEVASTATION = 51
SUPER_ADVENTURE_BOX = 935
TANGLED_DEPTHS = 1045
THE_CROWN_PAVILION = 929
THE_DESOLATION = 1226
THE_ECHOVALD_WILDS = 1452
THE_GROVE = 91
THE_SILVERWASTES = 1015
THE_WIZARDS_TOWER = 1509
THOUSAND_SEAS_PAVILION = 1465
THUNDERHEAD_PEAKS = 1310
TIMBERLINE_FALLS = 29
VERDANT_BRINK = 1052
WAYFARER_FOOTHILLS = 28
WINDSWEPT_HAVEN = 1215


central_tyria_map_ids=[ QUEENSDALE, HARATHI_HINTERLANDS, DIVINITYS_REACH,
    PLAINS_OF_ASHFORD, BLAZERIDGE_STEPPES, FIELDS_OF_RUIN, FIREHEART_RISE,
    KESSEX_HILLS, GENDARRAN_FIELDS, IRON_MARCHES, DREDGEHAUNT_CLIFFS,
    LORNARS_PASS, WAYFARER_FOOTHILLS, TIMBERLINE_FALLS, FROSTGORGE_SOUND,
    SNOWDEN_DRIFTS, DIESSA_PLATEAU, CALEDON_FOREST, METRICA_PROVINCE,
    MOUNT_MAELSTROM, LIONS_ARCH, STRAITS_OF_DEVASTATION, SPARKFLY_FEN,
    BRISBAN_WILDLANDS, CURSED_SHORE, MALCHORS_LEAP, BLOODTIDE_COAST, THE_GROVE, 
    RATA_SUM, BLACK_CITADEL, HOELBRAK, SOUTHSUN_COVE, DRY_TOP, THE_SILVERWASTES,
]


def _build_the_list_above():
    from api_request import get_api_json

    maps = get_api_json("https://api.guildwars2.com/v2/maps?ids=all")


    for map_data in maps:

        if map_data["type"] in ["Instance", "Pvp", "Unknown", "RedHome", "EdgeOfTheMists", "JumpPuzzle", "Tutorial", "BlueHome", "GreenHome", "Center"]:
            continue

        if map_data["name"].endswith("(Public)"):
            continue

        name = map_data["name"]#.upper()
        # name = name.replace(' ', '_')
        # name = ''.join([char for char in name if char.isupper() or char == '_'])

        print(name, "=", map_data["id"], map_data)
if __name__ == "__main__":
    _build_the_list_above()